/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DebtHolding {
  'id' : string,
  'principal' : number,
  'maturityDate' : string,
  'name' : string,
  'lastUpdated' : bigint,
  'currentValue' : number,
  'interestRate' : number,
  'debtType' : string,
  'startDate' : string,
}
export interface MutualFundHolding {
  'id' : string,
  'purchaseDate' : string,
  'lastUpdated' : bigint,
  'purchaseNAV' : number,
  'schemeCode' : string,
  'schemeName' : string,
  'units' : number,
  'currentNAV' : number,
}
export interface NpsHolding {
  'id' : string,
  'purchaseDate' : string,
  'tier' : string,
  'lastUpdated' : bigint,
  'purchaseNAV' : number,
  'schemeName' : string,
  'units' : number,
  'pfmId' : string,
  'currentNAV' : number,
}
export interface SgbHolding {
  'id' : string,
  'maturityDate' : string,
  'purchaseDate' : string,
  'name' : string,
  'lastUpdated' : bigint,
  'currentPricePerGram' : number,
  'units' : number,
  'issuePricePerGram' : number,
  'symbol' : string,
}
export interface StockHolding {
  'id' : string,
  'currentPrice' : number,
  'lastUpdated' : bigint,
  'buyDate' : string,
  'buyPrice' : number,
  'companyName' : string,
  'quantity' : number,
  'assetType' : string,
  'exchange' : string,
  'symbol' : string,
}
export interface Transaction {
  'id' : string,
  'transactionType' : string,
  'date' : string,
  'notes' : string,
  'quantity' : number,
  'assetName' : string,
  'assetType' : string,
  'price' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDebt' : ActorMethod<[DebtHolding], undefined>,
  'addMutualFund' : ActorMethod<[MutualFundHolding], undefined>,
  'addNps' : ActorMethod<[NpsHolding], undefined>,
  'addSgb' : ActorMethod<[SgbHolding], undefined>,
  'addStock' : ActorMethod<[StockHolding], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDebt' : ActorMethod<[string], boolean>,
  'deleteMutualFund' : ActorMethod<[string], boolean>,
  'deleteNps' : ActorMethod<[string], boolean>,
  'deleteSgb' : ActorMethod<[string], boolean>,
  'deleteStock' : ActorMethod<[string], boolean>,
  'deleteTransaction' : ActorMethod<[string], boolean>,
  'fetchMFData' : ActorMethod<[string], string>,
  'fetchNPSNav' : ActorMethod<[string], string>,
  'fetchStockPrice' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDebtHoldings' : ActorMethod<[], Array<DebtHolding>>,
  'getMutualFunds' : ActorMethod<[], Array<MutualFundHolding>>,
  'getNpsHoldings' : ActorMethod<[], Array<NpsHolding>>,
  'getSgbHoldings' : ActorMethod<[], Array<SgbHolding>>,
  'getStocks' : ActorMethod<[], Array<StockHolding>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMutualFunds' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDebt' : ActorMethod<[string, DebtHolding], boolean>,
  'updateMutualFund' : ActorMethod<[string, MutualFundHolding], boolean>,
  'updateNps' : ActorMethod<[string, NpsHolding], boolean>,
  'updateSgb' : ActorMethod<[string, SgbHolding], boolean>,
  'updateStock' : ActorMethod<[string, StockHolding], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];