/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DebtHolding = IDL.Record({
  'id' : IDL.Text,
  'principal' : IDL.Float64,
  'maturityDate' : IDL.Text,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'currentValue' : IDL.Float64,
  'interestRate' : IDL.Float64,
  'debtType' : IDL.Text,
  'startDate' : IDL.Text,
});
export const MutualFundHolding = IDL.Record({
  'id' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'purchaseNAV' : IDL.Float64,
  'schemeCode' : IDL.Text,
  'schemeName' : IDL.Text,
  'units' : IDL.Float64,
  'currentNAV' : IDL.Float64,
});
export const NpsHolding = IDL.Record({
  'id' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'tier' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'purchaseNAV' : IDL.Float64,
  'schemeName' : IDL.Text,
  'units' : IDL.Float64,
  'pfmId' : IDL.Text,
  'currentNAV' : IDL.Float64,
});
export const SgbHolding = IDL.Record({
  'id' : IDL.Text,
  'maturityDate' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'name' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'currentPricePerGram' : IDL.Float64,
  'units' : IDL.Float64,
  'issuePricePerGram' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const StockHolding = IDL.Record({
  'id' : IDL.Text,
  'currentPrice' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'buyDate' : IDL.Text,
  'buyPrice' : IDL.Float64,
  'companyName' : IDL.Text,
  'quantity' : IDL.Float64,
  'assetType' : IDL.Text,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'assetName' : IDL.Text,
  'assetType' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDebt' : IDL.Func([DebtHolding], [], []),
  'addMutualFund' : IDL.Func([MutualFundHolding], [], []),
  'addNps' : IDL.Func([NpsHolding], [], []),
  'addSgb' : IDL.Func([SgbHolding], [], []),
  'addStock' : IDL.Func([StockHolding], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDebt' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMutualFund' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteNps' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSgb' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteStock' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'fetchMFData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchNPSNav' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchStockPrice' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDebtHoldings' : IDL.Func([], [IDL.Vec(DebtHolding)], ['query']),
  'getMutualFunds' : IDL.Func([], [IDL.Vec(MutualFundHolding)], ['query']),
  'getNpsHoldings' : IDL.Func([], [IDL.Vec(NpsHolding)], ['query']),
  'getSgbHoldings' : IDL.Func([], [IDL.Vec(SgbHolding)], ['query']),
  'getStocks' : IDL.Func([], [IDL.Vec(StockHolding)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMutualFunds' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDebt' : IDL.Func([IDL.Text, DebtHolding], [IDL.Bool], []),
  'updateMutualFund' : IDL.Func([IDL.Text, MutualFundHolding], [IDL.Bool], []),
  'updateNps' : IDL.Func([IDL.Text, NpsHolding], [IDL.Bool], []),
  'updateSgb' : IDL.Func([IDL.Text, SgbHolding], [IDL.Bool], []),
  'updateStock' : IDL.Func([IDL.Text, StockHolding], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DebtHolding = IDL.Record({
    'id' : IDL.Text,
    'principal' : IDL.Float64,
    'maturityDate' : IDL.Text,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'currentValue' : IDL.Float64,
    'interestRate' : IDL.Float64,
    'debtType' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const MutualFundHolding = IDL.Record({
    'id' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'purchaseNAV' : IDL.Float64,
    'schemeCode' : IDL.Text,
    'schemeName' : IDL.Text,
    'units' : IDL.Float64,
    'currentNAV' : IDL.Float64,
  });
  const NpsHolding = IDL.Record({
    'id' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'tier' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'purchaseNAV' : IDL.Float64,
    'schemeName' : IDL.Text,
    'units' : IDL.Float64,
    'pfmId' : IDL.Text,
    'currentNAV' : IDL.Float64,
  });
  const SgbHolding = IDL.Record({
    'id' : IDL.Text,
    'maturityDate' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'name' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'currentPricePerGram' : IDL.Float64,
    'units' : IDL.Float64,
    'issuePricePerGram' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const StockHolding = IDL.Record({
    'id' : IDL.Text,
    'currentPrice' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'buyDate' : IDL.Text,
    'buyPrice' : IDL.Float64,
    'companyName' : IDL.Text,
    'quantity' : IDL.Float64,
    'assetType' : IDL.Text,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'assetName' : IDL.Text,
    'assetType' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDebt' : IDL.Func([DebtHolding], [], []),
    'addMutualFund' : IDL.Func([MutualFundHolding], [], []),
    'addNps' : IDL.Func([NpsHolding], [], []),
    'addSgb' : IDL.Func([SgbHolding], [], []),
    'addStock' : IDL.Func([StockHolding], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDebt' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMutualFund' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteNps' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSgb' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteStock' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'fetchMFData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchNPSNav' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchStockPrice' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDebtHoldings' : IDL.Func([], [IDL.Vec(DebtHolding)], ['query']),
    'getMutualFunds' : IDL.Func([], [IDL.Vec(MutualFundHolding)], ['query']),
    'getNpsHoldings' : IDL.Func([], [IDL.Vec(NpsHolding)], ['query']),
    'getSgbHoldings' : IDL.Func([], [IDL.Vec(SgbHolding)], ['query']),
    'getStocks' : IDL.Func([], [IDL.Vec(StockHolding)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMutualFunds' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDebt' : IDL.Func([IDL.Text, DebtHolding], [IDL.Bool], []),
    'updateMutualFund' : IDL.Func(
        [IDL.Text, MutualFundHolding],
        [IDL.Bool],
        [],
      ),
    'updateNps' : IDL.Func([IDL.Text, NpsHolding], [IDL.Bool], []),
    'updateSgb' : IDL.Func([IDL.Text, SgbHolding], [IDL.Bool], []),
    'updateStock' : IDL.Func([IDL.Text, StockHolding], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };